### ISSUE TITLE
problem installing all these software on both Ubuntu 14.04 and 16.04

### ISSUE THREAD

**Issue by aki72** [erlerobot/gym-gazebo#52]
I am doing as said in the installation procedure and have tried both the methods i.e. for Ubuntu 14.04 and 16.04 but its not getting properly installed. 
There is an import error that is arising when running the final python qlearn file and I am not able to figure out how to solve the issue in Ubuntu 16.04. Whenever I run the python code, it shows import error, gym not found, gym_gaezbo not found and so on.

Also after following the installation procedure given on Install.MD file for Ubuntu 14.04 and after running the turtlebot file, series of errors are produced saying no directory or file. I am stuck on this from so long. 

Please, tell me how can I rectify this issue in any one of the Ubuntu versions as I really need to work on these softwares.

**Comment by swordsgnat** [comment]
I was getting the "module gym not found" error for a while, too - it turned out to be because I had installed `gym` in Python 2.7 (that is, the `pip` I was using was defaulting to Python 2) which caused Python 3 to not know what I was talking about when I used it to try to run the qlearn files. When I updated my `pip` and went back and installed `gym` with `pip3`, it worked. As a starting point, I might check to be sure the Python version you're running the file with is the same as the one you installed everything in.
